specVersion: "0.3.0"

name: "Terra Contract Starter Project"
version: "1.0.0"
description: " "
repository: "https://github.com/subquery/tutorials-frontier-evm-starter"

schema:
  file: "./schema.graphql"

network:
  genesisHash: 'q4PIUU/W6KSxGM9wyowkSW+Ij8HuODDeM4USpA2ucWc='
  endpoint: 'http://terra.dc.thechainhub.com:1317/'
  chainId: 'columbus-5'

dataSources:
  - kind: terra/Runtime
    startBlock: 6837500
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleEvent
          kind: terra/EventHandler
          filter:
            contract: 'terra1j66jatn3k50hjtg2xemnjm8s7y8dws9xqa5y8w'
            type: transfer
        - handler: handleCall
          kind: terra/CallHandler
          filter:
            contract: 'terra1627ldjvxatt54ydd3ns6xaxtd68a2vtyu7kakj'
            function: claim_rewards_and_optionally_unlock
